import { NextResponse } from 'next/server';
import { cookies } from 'next/headers';
import { supabase } from '@/lib/supabase';

// Static data inline (from data/protocols.ts and data/programs.ts)
const protocols = [
  { id: 'safe-in-this-moment', title: 'Safe In This Moment', description: 'A gentle grounding session to help you feel safe and present wherever you are on your journey.', duration: 10, content_type: 'FULL SESSION', journeys: ['trying-to-conceive','pregnancy','pregnancy-recovery','postpartum'], emotional_states: ['struggling','doing-okay'], needs: ['calm','reassurance'], positions: ['sitting','lying'], has_visual: true, intention: 'Je choisis de me reconnecter à la sécurité de cet instant.', self_care_tip: 'Place one hand on your heart and one on your belly. Feel the warmth between your hands and your body.', is_support_now: false, parts: [{ label: 'Welcome', duration: '1 min', position: 0 }, { label: 'Breathing', duration: '2 min', position: 1 }, { label: 'Body Awareness', duration: '3 min', position: 2 }, { label: 'Visualization', duration: '3 min', position: 3 }, { label: 'Closing', duration: '1 min', position: 4 }] },
  { id: 'belly-breathing', title: 'Belly Breathing', description: 'A focused breathing practice to calm your nervous system and reconnect with your body.', duration: 5, content_type: 'REFLECT', journeys: ['trying-to-conceive','pregnancy','pregnancy-recovery','postpartum'], emotional_states: ['struggling','doing-okay','feeling-good'], needs: ['calm','rest'], positions: ['sitting','lying'], has_visual: true, intention: 'I breathe in calm and breathe out tension.', self_care_tip: 'Try this breathing technique before bed to help you drift into a restful sleep.', is_support_now: false, parts: [{ label: 'Welcome', duration: '1 min', position: 0 }, { label: 'Belly Breathing', duration: '3 min', position: 1 }, { label: 'Closing', duration: '1 min', position: 2 }] },
  { id: 'panic-reset', title: 'Panic Reset', description: 'An immediate grounding protocol to bring you back from overwhelm, quickly and gently.', duration: 3, content_type: 'PREPARE', journeys: ['trying-to-conceive','pregnancy','pregnancy-recovery','postpartum'], emotional_states: ['struggling'], needs: ['calm','reassurance'], positions: ['sitting','standing','lying'], has_visual: false, intention: 'This moment will pass. I am safe.', self_care_tip: 'After this session, drink a glass of cold water and name 5 things you can see.', is_support_now: true, support_now_key: 'panic', parts: [{ label: 'Grounding', duration: '1 min', position: 0 }, { label: '4-7-8 Breathing', duration: '1 min', position: 1 }, { label: 'Return', duration: '1 min', position: 2 }] },
  { id: 'waiting-room-calm', title: 'Waiting Room Calm', description: 'A discreet, eyes-open protocol you can use while sitting in any waiting room.', duration: 5, content_type: 'PREPARE', journeys: ['trying-to-conceive','pregnancy'], emotional_states: ['struggling','doing-okay'], needs: ['calm','confidence'], positions: ['sitting'], has_visual: false, intention: 'I am prepared. I am supported. I am enough.', self_care_tip: 'Keep your feet flat on the floor during appointments — it helps you stay grounded.', is_support_now: true, support_now_key: 'waiting-room', parts: [{ label: 'Settling', duration: '1 min', position: 0 }, { label: 'Breath Anchor', duration: '2 min', position: 1 }, { label: 'Positive Affirmation', duration: '1 min', position: 2 }, { label: 'Closing', duration: '1 min', position: 3 }] },
  { id: 'before-ultrasound', title: 'Before Ultrasound', description: 'Prepare your mind and body for the emotional experience of an ultrasound scan.', duration: 5, content_type: 'PREPARE', journeys: ['trying-to-conceive','pregnancy','pregnancy-recovery'], emotional_states: ['struggling','doing-okay','preparing-tomorrow'], needs: ['calm','reassurance','confidence'], positions: ['sitting','lying'], has_visual: false, intention: 'Whatever I see today, I will meet it with love.', self_care_tip: 'Bring a small comfort item to your appointment — a smooth stone or a photo.', is_support_now: true, support_now_key: 'before-ultrasound', parts: [{ label: 'Centering', duration: '1 min', position: 0 }, { label: 'Body Scan', duration: '2 min', position: 1 }, { label: 'Intention Setting', duration: '1 min', position: 2 }, { label: 'Closing', duration: '1 min', position: 3 }] },
  { id: 'before-embryo-transfer', title: 'Before Embryo Transfer', description: 'A special session to hold hope and reduce anxiety before your transfer.', duration: 8, content_type: 'PREPARE', journeys: ['trying-to-conceive'], emotional_states: ['struggling','doing-okay','preparing-tomorrow'], needs: ['calm','confidence','reassurance'], positions: ['lying'], has_visual: true, intention: 'I welcome this new beginning with open arms.', self_care_tip: 'Wear comfortable, warm clothing on the day of your transfer.', is_support_now: true, support_now_key: 'before-transfer', parts: [{ label: 'Welcome', duration: '1 min', position: 0 }, { label: 'Relaxation', duration: '3 min', position: 1 }, { label: 'Visualization', duration: '3 min', position: 2 }, { label: 'Closing', duration: '1 min', position: 3 }] },
  { id: 'waiting-for-results', title: 'Waiting for Results', description: 'Navigate the agonizing wait for test results with gentleness and self-compassion.', duration: 5, content_type: 'REFLECT', journeys: ['trying-to-conceive','pregnancy'], emotional_states: ['struggling','preparing-tomorrow'], needs: ['calm','reassurance','connection'], positions: ['sitting','lying'], has_visual: false, intention: 'I release what I cannot control and embrace what I can feel.', self_care_tip: 'During the wait, limit checking your phone to specific times — every 2 hours, not constantly.', is_support_now: true, support_now_key: 'waiting-results', parts: [{ label: 'Acknowledging', duration: '1 min', position: 0 }, { label: 'Breath Work', duration: '2 min', position: 1 }, { label: 'Self-Compassion', duration: '1 min', position: 2 }, { label: 'Closing', duration: '1 min', position: 3 }] },
  { id: 'sleep-reset', title: 'Sleep Reset', description: 'Release the day and prepare your body and mind for deep, restorative sleep.', duration: 8, content_type: 'REFLECT', journeys: ['trying-to-conceive','pregnancy','pregnancy-recovery','postpartum'], emotional_states: ['struggling','doing-okay','moment-for-myself'], needs: ['rest','calm'], positions: ['lying'], has_visual: true, intention: 'I give my body permission to rest completely.', self_care_tip: 'Keep your room cool and dark. A lavender pillow mist can deepen relaxation.', is_support_now: true, support_now_key: 'sleep', parts: [{ label: 'Body Release', duration: '2 min', position: 0 }, { label: 'Breath Slow-Down', duration: '2 min', position: 1 }, { label: 'Visualization', duration: '3 min', position: 2 }, { label: 'Drift', duration: '1 min', position: 3 }] },
  { id: 'morning-gentle-start', title: 'Morning Gentle Start', description: 'Begin your day with calm intention and a soft connection to your body.', duration: 10, content_type: 'REFLECT', journeys: ['pregnancy','postpartum'], emotional_states: ['doing-okay','feeling-good','preparing-tomorrow'], needs: ['calm','confidence','connection'], positions: ['sitting','lying'], has_visual: true, intention: 'Today I move gently and with grace.', self_care_tip: "Before getting out of bed, take 3 deep breaths and smile — even if you don't feel like it.", is_support_now: false, parts: [{ label: 'Waking Breath', duration: '2 min', position: 0 }, { label: 'Body Appreciation', duration: '3 min', position: 1 }, { label: 'Intention', duration: '2 min', position: 2 }, { label: 'Motivation', duration: '2 min', position: 3 }, { label: 'Closing', duration: '1 min', position: 4 }] },
  { id: 'confidence-boost', title: 'Confidence Boost', description: "Reconnect with your inner strength and trust your body's wisdom.", duration: 10, content_type: 'FULL SESSION', journeys: ['trying-to-conceive','pregnancy','postpartum'], emotional_states: ['doing-okay','feeling-good','preparing-tomorrow'], needs: ['confidence','connection'], positions: ['sitting','standing'], has_visual: false, intention: 'I trust my body. I trust my journey.', self_care_tip: 'Write down 3 things your body has done amazingly well this week.', is_support_now: false, parts: [{ label: 'Centering', duration: '2 min', position: 0 }, { label: 'Strength Meditation', duration: '3 min', position: 1 }, { label: 'Affirmations', duration: '3 min', position: 2 }, { label: 'Closing', duration: '2 min', position: 3 }] },
  { id: 'gentle-movement', title: 'Gentle Movement', description: 'A mindful movement session to release tension and connect with your changing body.', duration: 15, content_type: 'MOVE', journeys: ['pregnancy','postpartum'], emotional_states: ['doing-okay','feeling-good','moment-for-myself'], needs: ['rest','connection','calm'], positions: ['standing','sitting'], has_visual: true, intention: 'I move with love and listen to what my body needs.', self_care_tip: 'Move only as far as feels comfortable. Rest is also movement.', is_support_now: false, parts: [{ label: 'Warm Up', duration: '3 min', position: 0 }, { label: 'Gentle Stretches', duration: '5 min', position: 1 }, { label: 'Breathing Movement', duration: '4 min', position: 2 }, { label: 'Cool Down', duration: '3 min', position: 3 }] },
  { id: 'moment-for-myself', title: 'A Moment For Myself', description: 'Pure self-care — a space that exists just for you, no agenda, no outcomes.', duration: 15, content_type: 'REFLECT', journeys: ['trying-to-conceive','pregnancy','pregnancy-recovery','postpartum'], emotional_states: ['moment-for-myself','feeling-good'], needs: ['rest','connection','calm'], positions: ['sitting','lying'], has_visual: true, intention: 'Right now, I exist only for myself.', self_care_tip: 'After this session, treat yourself to something small and beautiful — herbal tea, a warm bath, or fresh flowers.', is_support_now: false, parts: [{ label: 'Arrival', duration: '2 min', position: 0 }, { label: 'Body Scan', duration: '4 min', position: 1 }, { label: 'Visualization', duration: '5 min', position: 2 }, { label: 'Gratitude', duration: '2 min', position: 3 }, { label: 'Return', duration: '2 min', position: 4 }] },
  { id: 'connection-with-baby', title: 'Connecting With Baby', description: 'A tender session to deepen your bond with your baby through voice, touch and visualization.', duration: 10, content_type: 'FULL SESSION', journeys: ['pregnancy'], emotional_states: ['doing-okay','feeling-good','moment-for-myself'], needs: ['connection','calm'], positions: ['sitting','lying'], has_visual: true, intention: 'I speak to my baby with love, and they feel me.', self_care_tip: 'Play soft music or hum gently — your baby can hear you and feel the vibrations.', is_support_now: false, parts: [{ label: 'Settling', duration: '2 min', position: 0 }, { label: 'Breath Together', duration: '2 min', position: 1 }, { label: 'Speaking to Baby', duration: '3 min', position: 2 }, { label: 'Visualization', duration: '2 min', position: 3 }, { label: 'Closing', duration: '1 min', position: 4 }] },
  { id: 'releasing-fear', title: 'Releasing Fear', description: 'Gently acknowledge and release fears about birth, parenthood, or the unknown.', duration: 15, content_type: 'REFLECT', journeys: ['pregnancy','pregnancy-recovery'], emotional_states: ['struggling','doing-okay'], needs: ['reassurance','calm','confidence'], positions: ['sitting','lying'], has_visual: false, intention: 'I acknowledge my fear and choose courage.', self_care_tip: 'Write your fears on paper, then fold the paper and put it away — symbolically setting them aside.', is_support_now: false, parts: [{ label: 'Welcome', duration: '2 min', position: 0 }, { label: 'Naming Fears', duration: '3 min', position: 1 }, { label: 'Release Visualization', duration: '5 min', position: 2 }, { label: 'Affirmation', duration: '3 min', position: 3 }, { label: 'Closing', duration: '2 min', position: 4 }] },
  { id: 'gentle-return', title: 'Gentle Return', description: 'A compassionate session for those returning to pregnancy after loss.', duration: 10, content_type: 'FULL SESSION', journeys: ['pregnancy-recovery','pregnancy'], emotional_states: ['struggling','doing-okay'], needs: ['reassurance','calm','connection'], positions: ['sitting','lying'], has_visual: true, intention: 'I carry all my love forward. I am allowed to hope.', self_care_tip: 'Be gentle with yourself today. There is no right or wrong way to feel.', is_support_now: false, parts: [{ label: 'Acknowledgement', duration: '2 min', position: 0 }, { label: 'Breathing', duration: '2 min', position: 1 }, { label: 'Grief and Hope', duration: '3 min', position: 2 }, { label: 'Visualization', duration: '2 min', position: 3 }, { label: 'Closing', duration: '1 min', position: 4 }] },
  { id: 'postpartum-welcome-back', title: 'Welcome Back To Yourself', description: 'Begin reconnecting with who you are beyond being a mother — with gentleness and curiosity.', duration: 10, content_type: 'REFLECT', journeys: ['postpartum'], emotional_states: ['doing-okay','moment-for-myself','struggling'], needs: ['connection','rest','reassurance'], positions: ['sitting','lying'], has_visual: true, intention: 'I am more than a mother. I am still myself.', self_care_tip: 'Do one thing today that is purely for you — not for baby, not for family. Just you.', is_support_now: false, parts: [{ label: 'Arrival', duration: '2 min', position: 0 }, { label: 'Body Recognition', duration: '3 min', position: 1 }, { label: 'Self Identity', duration: '3 min', position: 2 }, { label: 'Closing', duration: '2 min', position: 3 }] },
  { id: 'one-step-at-a-time', title: 'One Step At A Time', description: 'When everything feels like too much, this session helps you return to the present moment and take things one breath at a time.', duration: 10, content_type: 'REFLECT', journeys: ['trying-to-conceive','pregnancy','pregnancy-recovery','postpartum'], emotional_states: ['struggling','doing-okay'], needs: ['calm','reassurance'], positions: ['sitting','lying'], has_visual: false, intention: 'I only need to manage this one moment.', self_care_tip: 'Write down the single next small step. Just one. Nothing beyond that.', is_support_now: false, parts: [{ label: 'Grounding', duration: '2 min', position: 0 }, { label: 'Breath Anchor', duration: '3 min', position: 1 }, { label: 'Present Focus', duration: '3 min', position: 2 }, { label: 'Closing', duration: '2 min', position: 3 }] },
  { id: 'hope-through-uncertainty', title: 'Hope Through Uncertainty', description: 'Hold space for hope and uncertainty at the same time — because both are allowed.', duration: 12, content_type: 'FULL SESSION', journeys: ['trying-to-conceive','pregnancy-recovery'], emotional_states: ['struggling','doing-okay','preparing-tomorrow'], needs: ['reassurance','calm','connection'], positions: ['sitting','lying'], has_visual: true, intention: 'I hold hope gently, without forcing certainty.', self_care_tip: 'Allow yourself to hope. Hope is not naivety — it is courage.', is_support_now: false, parts: [{ label: 'Welcome', duration: '1 min', position: 0 }, { label: 'Naming What Is', duration: '3 min', position: 1 }, { label: 'Breath for Hope', duration: '3 min', position: 2 }, { label: 'Visualization', duration: '4 min', position: 3 }, { label: 'Closing', duration: '1 min', position: 4 }] },
  { id: 'releasing-control', title: 'Releasing Control', description: 'A gentle practice to soften the need to control outcomes and rest in what is possible.', duration: 10, content_type: 'REFLECT', journeys: ['trying-to-conceive','pregnancy','pregnancy-recovery','postpartum'], emotional_states: ['struggling','doing-okay'], needs: ['calm','reassurance'], positions: ['sitting','lying'], has_visual: false, intention: 'I release what I cannot change and trust in this process.', self_care_tip: 'Write down what you can control today, and let the rest go on paper.', is_support_now: false, parts: [{ label: 'Opening', duration: '1 min', position: 0 }, { label: 'Tension Release', duration: '3 min', position: 1 }, { label: 'Letting Go', duration: '4 min', position: 2 }, { label: 'Return', duration: '2 min', position: 3 }] },
  { id: 'birth-preparation', title: 'Birth Preparation', description: 'Prepare your mind and body for birth with confidence, calm and deep body trust.', duration: 15, content_type: 'PREPARE', journeys: ['pregnancy'], emotional_states: ['doing-okay','feeling-good','preparing-tomorrow'], needs: ['confidence','calm','connection'], positions: ['sitting','lying'], has_visual: true, intention: 'My body knows how to do this. I trust the process.', self_care_tip: 'Practice your birth affirmations daily — place them somewhere visible.', is_support_now: false, parts: [{ label: 'Welcome', duration: '2 min', position: 0 }, { label: 'Body Scan', duration: '3 min', position: 1 }, { label: 'Visualization of Birth', duration: '5 min', position: 2 }, { label: 'Affirmations', duration: '3 min', position: 3 }, { label: 'Closing', duration: '2 min', position: 4 }] },
  { id: 'partner-connection', title: 'Partner Connection', description: 'A guided practice to deepen the connection between you and your partner during this journey.', duration: 10, content_type: 'FULL SESSION', journeys: ['pregnancy','postpartum'], emotional_states: ['doing-okay','feeling-good','moment-for-myself'], needs: ['connection','calm'], positions: ['sitting','lying'], has_visual: false, intention: 'We are in this together, held by love.', self_care_tip: 'Share one thing you are grateful for about your partner before you sleep tonight.', is_support_now: false, parts: [{ label: 'Arrival Together', duration: '2 min', position: 0 }, { label: 'Synchronized Breathing', duration: '3 min', position: 1 }, { label: 'Intention for Two', duration: '3 min', position: 2 }, { label: 'Closing', duration: '2 min', position: 3 }] },
  { id: 'grief-and-healing', title: 'Grief and Healing', description: 'A compassionate space to honor grief, acknowledge loss, and begin to gently heal.', duration: 15, content_type: 'REFLECT', journeys: ['pregnancy-recovery'], emotional_states: ['struggling','doing-okay'], needs: ['reassurance','calm','connection'], positions: ['sitting','lying'], has_visual: false, intention: 'My grief is valid. My healing is possible. Both are true.', self_care_tip: 'Grief has no timeline. Be as patient with yourself as you would be with someone you love.', is_support_now: false, parts: [{ label: 'Safe Space', duration: '2 min', position: 0 }, { label: 'Acknowledging Loss', duration: '4 min', position: 1 }, { label: 'Breath for Healing', duration: '4 min', position: 2 }, { label: 'Compassion Practice', duration: '3 min', position: 3 }, { label: 'Closing', duration: '2 min', position: 4 }] },
  { id: 'cycle-calm', title: 'Before Your Treatment Cycle', description: 'Calm your mind and body as you step into a new treatment cycle.', duration: 10, content_type: 'PREPARE', journeys: ['fertility-treatment','trying-to-conceive'], emotional_states: ['struggling','doing-okay','preparing-tomorrow'], needs: ['calm','reassurance','prepare'], positions: ['sitting','lying'], has_visual: false, intention: 'I enter this cycle with an open and calm heart.', self_care_tip: 'Write a letter to your future self before each cycle. Open it after.', is_support_now: false, parts: [{ label: 'Settling', duration: '2 min', position: 0 }, { label: 'Breath Anchor', duration: '3 min', position: 1 }, { label: 'Body Readiness', duration: '3 min', position: 2 }, { label: 'Closing', duration: '2 min', position: 3 }] },
  { id: 'two-week-wait', title: 'The Two-Week Wait', description: 'Navigate the emotional intensity of waiting with gentleness and self-compassion.', duration: 12, content_type: 'REFLECT', journeys: ['fertility-treatment','trying-to-conceive'], emotional_states: ['struggling','doing-okay','preparing-tomorrow'], needs: ['calm','reassurance'], positions: ['sitting','lying'], has_visual: true, intention: 'I trust my body and I allow this moment to simply be.', self_care_tip: 'Create a two-week wait ritual — one small joy to look forward to each day.', is_support_now: false, parts: [{ label: 'Welcome', duration: '2 min', position: 0 }, { label: 'Breath for Waiting', duration: '3 min', position: 1 }, { label: 'Body Trust', duration: '4 min', position: 2 }, { label: 'Visualization', duration: '2 min', position: 3 }, { label: 'Closing', duration: '1 min', position: 4 }] },
  { id: 'bed-rest-peace', title: 'Peace in Rest', description: 'Find calm and meaning during enforced rest, staying connected to your baby and yourself.', duration: 8, content_type: 'REFLECT', journeys: ['difficult-pregnancy'], emotional_states: ['struggling','doing-okay'], needs: ['calm','rest','reconnect-self'], positions: ['lying'], has_visual: true, intention: 'My rest is not surrender — it is love in action.', self_care_tip: 'Rest is your work right now. Let that be enough.', is_support_now: false, parts: [{ label: 'Body Softening', duration: '2 min', position: 0 }, { label: 'Breath Connection', duration: '2 min', position: 1 }, { label: 'Visualization', duration: '3 min', position: 2 }, { label: 'Closing', duration: '1 min', position: 3 }] },
  { id: 'uncertainty-anchor', title: 'Your Anchor in Uncertainty', description: 'Find your inner anchor when the outcome is unknown and fear takes hold.', duration: 10, content_type: 'FULL SESSION', journeys: ['difficult-pregnancy','waiting','fertility-treatment'], emotional_states: ['struggling','doing-okay'], needs: ['face-challenge','reassurance','calm'], positions: ['sitting','lying'], has_visual: false, intention: 'In uncertainty, I find my anchor within.', self_care_tip: 'Identify one constant in your life right now and return to it often.', is_support_now: false, parts: [{ label: 'Grounding', duration: '2 min', position: 0 }, { label: 'Naming What Is', duration: '2 min', position: 1 }, { label: 'Finding the Anchor', duration: '4 min', position: 2 }, { label: 'Closing', duration: '2 min', position: 3 }] },
  { id: 'waiting-with-grace', title: 'Waiting With Grace', description: 'A practice for the hardest skill — waiting without knowing, and finding peace within it.', duration: 8, content_type: 'REFLECT', journeys: ['waiting','fertility-treatment','trying-to-conceive','difficult-pregnancy'], emotional_states: ['struggling','doing-okay','preparing-tomorrow'], needs: ['calm','reassurance'], positions: ['sitting','lying'], has_visual: false, intention: 'I wait with grace, knowing this moment too shall pass.', self_care_tip: 'Designate a "waiting hour" — feel it fully, then close it for the day.', is_support_now: true, support_now_key: 'waiting', parts: [{ label: 'Arriving', duration: '1 min', position: 0 }, { label: 'Breath of Patience', duration: '3 min', position: 1 }, { label: 'Inner Peace', duration: '3 min', position: 2 }, { label: 'Closing', duration: '1 min', position: 3 }] },
  { id: 'birth-breathing', title: 'Breathing Through Birth', description: 'Practice the breathing techniques that will support you through every stage of labour.', duration: 12, content_type: 'PREPARE', journeys: ['birth-preparation','pregnancy'], emotional_states: ['doing-okay','feeling-good','preparing-tomorrow'], needs: ['prepare','calm','confidence'], positions: ['sitting','lying'], has_visual: true, intention: 'Each breath is a wave. I ride it with strength.', self_care_tip: 'Practice daily in the last weeks — breathing for birth becomes instinctive.', is_support_now: false, parts: [{ label: 'Introduction', duration: '1 min', position: 0 }, { label: 'Slow Breathing', duration: '3 min', position: 1 }, { label: 'Active Breathing', duration: '4 min', position: 2 }, { label: 'Transition Breath', duration: '3 min', position: 3 }, { label: 'Closing', duration: '1 min', position: 4 }] },
  { id: 'labor-support', title: 'In This Moment', description: 'A brief, grounding support for the intensity of active labour — breathe, soften, stay present.', duration: 5, content_type: 'PREPARE', journeys: ['birth'], emotional_states: ['struggling','doing-okay'], needs: ['calm','face-challenge'], positions: ['sitting','standing','lying'], has_visual: false, intention: 'This moment is strong. So am I.', self_care_tip: 'Between contractions, let your body go completely soft. Save your energy for each wave.', is_support_now: true, support_now_key: 'labor', parts: [{ label: 'Ground', duration: '1 min', position: 0 }, { label: 'Breathe Through', duration: '2 min', position: 1 }, { label: 'Release', duration: '2 min', position: 2 }] },
  { id: 'healing-birth-story', title: 'Healing Your Birth Story', description: "A compassionate space to process and heal when your birth didn't go as planned.", duration: 15, content_type: 'REFLECT', journeys: ['birth','postpartum','pregnancy-recovery'], emotional_states: ['struggling','doing-okay'], needs: ['welcome-emotions','face-challenge','reconnect-self'], positions: ['sitting','lying'], has_visual: false, intention: 'My birth story is mine. I hold it with compassion.', self_care_tip: 'Write your birth story in three chapters: what you hoped, what happened, what you felt.', is_support_now: false, parts: [{ label: 'Welcome', duration: '2 min', position: 0 }, { label: 'What Happened', duration: '3 min', position: 1 }, { label: 'What You Felt', duration: '4 min', position: 2 }, { label: 'Compassion', duration: '4 min', position: 3 }, { label: 'Closing', duration: '2 min', position: 4 }] },
  { id: 'holding-loss', title: 'Holding What Was Lost', description: 'A gentle space to acknowledge your grief, honor your loss, and begin to carry it with love.', duration: 12, content_type: 'FULL SESSION', journeys: ['perinatal-grief','pregnancy-recovery'], emotional_states: ['struggling','doing-okay'], needs: ['welcome-emotions','face-challenge'], positions: ['sitting','lying'], has_visual: false, intention: 'I hold what was lost with the love it always deserved.', self_care_tip: 'There is no right way to grieve. Allow your grief to have whatever shape it needs.', is_support_now: false, parts: [{ label: 'Safe Space', duration: '2 min', position: 0 }, { label: 'Presence', duration: '3 min', position: 1 }, { label: 'Acknowledgement', duration: '4 min', position: 2 }, { label: 'Love', duration: '2 min', position: 3 }, { label: 'Closing', duration: '1 min', position: 4 }] },
  { id: 'remembering', title: 'A Space to Remember', description: 'Create a moment of connection with what was lost — to remember, to honor, to carry forward.', duration: 10, content_type: 'REFLECT', journeys: ['perinatal-grief','pregnancy-recovery'], emotional_states: ['struggling','doing-okay'], needs: ['welcome-emotions','reconnect-self'], positions: ['sitting','lying'], has_visual: true, intention: 'I remember with love. Love does not end with loss.', self_care_tip: 'Create a small ritual to honor your loss — a candle, a plant, a dedicated moment.', is_support_now: false, parts: [{ label: 'Centering', duration: '2 min', position: 0 }, { label: 'Remembering', duration: '4 min', position: 1 }, { label: 'Honoring', duration: '3 min', position: 2 }, { label: 'Closing', duration: '1 min', position: 3 }] },
  { id: 'daily-bloom', title: 'Daily Bloom', description: 'A gentle daily practice to develop your inner resources and fully inhabit your pregnancy.', duration: 10, content_type: 'REFLECT', journeys: ['feeling-well','pregnancy','postpartum'], emotional_states: ['feeling-good','doing-okay','moment-for-myself'], needs: ['develop-resources','connection','calm'], positions: ['sitting','lying'], has_visual: true, intention: 'Today I grow, quietly and completely.', self_care_tip: 'Notice one moment of beauty today — something small, something yours.', is_support_now: false, parts: [{ label: 'Arrival', duration: '2 min', position: 0 }, { label: 'Inner Resource', duration: '3 min', position: 1 }, { label: 'Visualization', duration: '3 min', position: 2 }, { label: 'Closing', duration: '2 min', position: 3 }] },
  { id: 'finding-me-again', title: 'Finding Me Again', description: 'A journey back to yourself — beyond the roles, the expectations, the changes.', duration: 15, content_type: 'FULL SESSION', journeys: ['postpartum','feeling-well','pregnancy-recovery'], emotional_states: ['doing-okay','moment-for-myself','feeling-good'], needs: ['reconnect-self','develop-resources'], positions: ['sitting','lying'], has_visual: true, intention: 'I am still here. I have always been here.', self_care_tip: 'List five things you loved before becoming a mother. Do one this week.', is_support_now: false, parts: [{ label: 'Welcome Home', duration: '2 min', position: 0 }, { label: 'Body Return', duration: '3 min', position: 1 }, { label: 'Who I Am', duration: '5 min', position: 2 }, { label: 'Affirmation', duration: '3 min', position: 3 }, { label: 'Closing', duration: '2 min', position: 4 }] },
  { id: 'finding-my-place', title: 'Finding My Place', description: 'A grounding session to help you find your role, your presence, and your strength as a partner.', duration: 10, content_type: 'FULL SESSION', journeys: ['pregnancy','trying-to-conceive','postpartum','perinatal-grief','fertility-treatment'], emotional_states: ['doing-okay','struggling'], needs: ['confidence','reconnect-self','connection'], positions: ['sitting'], has_visual: false, intention: 'I am exactly where I need to be.', self_care_tip: 'Ask her what feels most supportive today — the answer may surprise you.', is_support_now: false, for_lounge: 'partner', parts: [{ label: 'Centering', duration: '2 min', position: 0 }, { label: 'Your Role', duration: '3 min', position: 1 }, { label: 'Strength', duration: '3 min', position: 2 }, { label: 'Closing', duration: '2 min', position: 3 }] },
  { id: 'supporting-without-losing-self', title: 'Supporting Without Losing Yourself', description: 'Learn to hold space for someone you love without disappearing into that role.', duration: 12, content_type: 'REFLECT', journeys: ['pregnancy','fertility-treatment','postpartum','perinatal-grief'], emotional_states: ['struggling','doing-okay'], needs: ['reconnect-self','develop-resources','face-challenge'], positions: ['sitting','lying'], has_visual: false, intention: 'I can support with fullness only when I am full.', self_care_tip: 'Identify one thing that refills you. Protect that time.', is_support_now: false, for_lounge: 'partner', parts: [{ label: 'Arrival', duration: '2 min', position: 0 }, { label: "What You're Carrying", duration: '3 min', position: 1 }, { label: 'Your Needs Too', duration: '4 min', position: 2 }, { label: 'Balance', duration: '2 min', position: 3 }, { label: 'Closing', duration: '1 min', position: 4 }] },
  { id: 'partner-in-waiting', title: 'Waiting Together', description: "A practice for the agonizing wait — for results, for birth, for news — from the partner's side.", duration: 8, content_type: 'REFLECT', journeys: ['trying-to-conceive','fertility-treatment','pregnancy','perinatal-grief'], emotional_states: ['struggling','doing-okay','preparing-tomorrow'], needs: ['calm','reassurance','face-challenge'], positions: ['sitting','lying'], has_visual: false, intention: 'We wait together, and together we are stronger.', self_care_tip: "You don't need the perfect words. Being present is the most powerful thing you can offer.", is_support_now: false, for_lounge: 'partner', parts: [{ label: 'Acknowledging', duration: '1 min', position: 0 }, { label: 'Breath for Two', duration: '3 min', position: 1 }, { label: 'Being Present', duration: '3 min', position: 2 }, { label: 'Closing', duration: '1 min', position: 3 }] },
  { id: 'partner-grief-space', title: 'A Space for Your Grief Too', description: 'Your grief is real and valid — this session gives it the space it deserves.', duration: 12, content_type: 'FULL SESSION', journeys: ['perinatal-grief','pregnancy-recovery'], emotional_states: ['struggling','doing-okay'], needs: ['welcome-emotions','face-challenge'], positions: ['sitting','lying'], has_visual: false, intention: 'I am allowed to grieve too. This loss is mine to carry.', self_care_tip: "You don't have to be strong every minute. Find one person you can be vulnerable with.", is_support_now: false, for_lounge: 'partner', parts: [{ label: 'Permission', duration: '2 min', position: 0 }, { label: 'What You Feel', duration: '3 min', position: 1 }, { label: 'Honouring', duration: '4 min', position: 2 }, { label: 'Compassion', duration: '2 min', position: 3 }, { label: 'Closing', duration: '1 min', position: 4 }] },
  { id: 'ready-for-birth', title: 'Ready For This', description: 'Prepare yourself mentally and emotionally to be fully present on birth day.', duration: 8, content_type: 'PREPARE', journeys: ['pregnancy','birth-preparation','birth'], emotional_states: ['doing-okay','feeling-good','preparing-tomorrow'], needs: ['prepare','confidence','calm'], positions: ['sitting'], has_visual: false, intention: 'I show up fully, for her and for us.', self_care_tip: 'Know her birth preferences by heart. That knowledge is your superpower in the room.', is_support_now: false, for_lounge: 'partner', parts: [{ label: 'Centering', duration: '1 min', position: 0 }, { label: 'Your Role', duration: '3 min', position: 1 }, { label: 'Readiness', duration: '3 min', position: 2 }, { label: 'Closing', duration: '1 min', position: 3 }] },
];

const programs = [
  { id: 'ivf-journey', title: 'IVF Journey', description: 'Support through every stage of IVF — from preparation to the two-week wait.', journey: 'trying-to-conceive', lounge: null, is_premium: false, sessions: [{ id: 'ivf-1', label: 'Grounding Before Your Appointment', protocol_id: 'waiting-room-calm', position_x: 0 }, { id: 'ivf-2', label: 'Before Egg Retrieval', protocol_id: 'before-ultrasound', position_x: 250 }, { id: 'ivf-3', label: 'Waiting Room Calm', protocol_id: 'waiting-room-calm', position_x: 500 }, { id: 'ivf-4', label: 'After the Transfer — Waiting in Hope', protocol_id: 'waiting-for-results', position_x: 750 }] },
  { id: 'pregnancy-after-loss', title: 'Pregnancy After Loss', description: 'Gentle support for navigating a new pregnancy after the experience of loss.', journey: 'pregnancy-recovery', lounge: null, is_premium: false, sessions: [{ id: 'pal-1', label: 'Gentle Return', protocol_id: 'gentle-return', position_x: 0 }, { id: 'pal-2', label: 'Meeting Your Body Again', protocol_id: 'safe-in-this-moment', position_x: 250 }, { id: 'pal-3', label: 'Holding Two Truths', protocol_id: 'releasing-fear', position_x: 500 }, { id: 'pal-4', label: 'Preparing for What\'s Next', protocol_id: 'confidence-boost', position_x: 750 }] },
  { id: 'preparing-for-birth', title: 'Preparing For Birth', description: 'Build confidence, calm and connection as you approach the birth of your baby.', journey: 'pregnancy', lounge: null, is_premium: false, sessions: [{ id: 'pfb-1', label: 'Birth Preparation', protocol_id: 'releasing-fear', position_x: 0 }, { id: 'pfb-2', label: 'Releasing Fear', protocol_id: 'releasing-fear', position_x: 250 }, { id: 'pfb-3', label: 'Connecting with Baby', protocol_id: 'connection-with-baby', position_x: 500 }, { id: 'pfb-4', label: 'The Birth Space', protocol_id: 'confidence-boost', position_x: 750 }] },
  { id: 'returning-to-myself', title: 'Returning To Myself', description: 'A postpartum journey back to yourself — body, mind and identity.', journey: 'postpartum', lounge: null, is_premium: false, sessions: [{ id: 'rtm-1', label: 'Welcome Back', protocol_id: 'postpartum-welcome-back', position_x: 0 }, { id: 'rtm-2', label: 'Gentle Awakening', protocol_id: 'morning-gentle-start', position_x: 250 }, { id: 'rtm-3', label: 'Rebuilding Strength', protocol_id: 'gentle-movement', position_x: 500 }, { id: 'rtm-4', label: 'Finding Your New Self', protocol_id: 'moment-for-myself', position_x: 750 }] },
  { id: 'the-partners-path', title: "The Partner's Path", description: 'Four sessions to help you find your place, stay present, and support without losing yourself.', journey: 'pregnancy', lounge: 'partner', is_premium: false, sessions: [{ id: 'pp-1', label: 'Finding My Place', protocol_id: 'finding-my-place', position_x: 0 }, { id: 'pp-2', label: 'Supporting Without Losing Self', protocol_id: 'supporting-without-losing-self', position_x: 250 }, { id: 'pp-3', label: 'Waiting Together', protocol_id: 'partner-in-waiting', position_x: 500 }, { id: 'pp-4', label: 'Ready For This', protocol_id: 'ready-for-birth', position_x: 750 }] },
];

export async function GET() {
  const cookieStore = await cookies();
  if (!cookieStore.get('admin_session')) {
    return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
  }

  const results: string[] = [];

  // Upsert protocols
  for (const p of protocols) {
    const { parts, ...proto } = p;
    const { error: pe } = await supabase.from('protocols').upsert(proto, { onConflict: 'id' });
    if (pe) { results.push(`ERROR protocol ${p.id}: ${pe.message}`); continue; }

    // Delete old parts and re-insert
    await supabase.from('protocol_parts').delete().eq('protocol_id', p.id);
    for (const part of parts) {
      const { error: pte } = await supabase.from('protocol_parts').insert({
        protocol_id: p.id,
        label: part.label,
        duration: part.duration,
        position: part.position,
      });
      if (pte) results.push(`ERROR part ${p.id}/${part.label}: ${pte.message}`);
    }
    results.push(`OK protocol: ${p.id}`);
  }

  // Upsert programs + flow nodes
  for (const prog of programs) {
    const { sessions, ...program } = prog;
    const { error: proge } = await supabase.from('programs').upsert(program, { onConflict: 'id' });
    if (proge) { results.push(`ERROR program ${prog.id}: ${proge.message}`); continue; }

    // Delete old flow nodes and re-insert
    await supabase.from('flow_nodes').delete().eq('program_id', prog.id);
    for (const s of sessions) {
      const { error: ne } = await supabase.from('flow_nodes').insert({
        id: s.id,
        program_id: prog.id,
        protocol_id: s.protocol_id,
        label: s.label,
        type: 'session',
        position_x: s.position_x,
        position_y: 100,
      });
      if (ne) results.push(`ERROR node ${s.id}: ${ne.message}`);
    }
    results.push(`OK program: ${prog.id}`);
  }

  return NextResponse.json({ seeded: results.length, results });
}
